# Generated by Django 2.0.1 on 2020-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment_time', models.DateField(blank=True, null=True)),
                ('comment_content', models.CharField(blank=True, max_length=200, null=True)),
                ('satisfaction', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feedback_suggest', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback_content', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback_img', models.CharField(blank=True, max_length=256, null=True)),
                ('feedback_phone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, blank=True)),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('link_url', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(0, '审核中'), (1, '已通过'), (2, '未通过')], default=0)),
            ],
            options={
                'db_table': 'message',
                'ordering': ['-create_time'],
                'managed': False,
            },
        ),
    ]
