# Generated by Django 2.0.1 on 2020-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=10)),
                ('intergration', models.IntegerField()),
            ],
            options={
                'db_table': 'grade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_img', models.CharField(blank=True, max_length=256, null=True)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_phone', models.IntegerField()),
                ('user_datetime', models.DateField()),
                ('isactive', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=256)),
                ('telephone', models.IntegerField()),
            ],
            options={
                'db_table': 'user_address',
                'managed': False,
            },
        ),
    ]
