# Generated by Django 2.0.1 on 2020-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ident_msg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('indent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('indent_time', models.DateField()),
                ('indent_price', models.FloatField()),
                ('indent_state', models.IntegerField()),
            ],
            options={
                'db_table': 'indent',
                'managed': False,
            },
        ),
    ]
