# Generated by Django 2.0.1 on 2020-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.IntegerField(primary_key=True, serialize=False)),
                ('discount_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_img', models.CharField(blank=True, max_length=256, null=True)),
                ('product_name', models.CharField(max_length=20)),
                ('product_priceout', models.FloatField()),
                ('product_longname', models.CharField(blank=True, max_length=20, null=True)),
                ('product_makeprice', models.FloatField()),
                ('product_storenum', models.IntegerField()),
                ('product_numout', models.IntegerField()),
                ('product_time', models.DateField()),
                ('product_expiretime', models.DateField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_factory', models.CharField(max_length=20)),
                ('source_total', models.IntegerField()),
                ('source_price', models.FloatField()),
                ('source_all_price', models.FloatField()),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
    ]
