# Generated by Django 2.0.1 on 2020-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('carts_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shopnumber', models.IntegerField()),
            ],
            options={
                'db_table': 'carts',
                'managed': False,
            },
        ),
    ]
